### ISSUE TITLE
too evil

### ISSUE THREAD

**Issue by jooapa** [miskamero/explorer-kill-on-startup#4]
this very program is too evil to be on github. i am very offended from this, and i will be taking legal actions if this program is not removed. you'll be hearing from my lawyers soon.

**Comment by miskamero** [comment]
Thank you for expressing your concerns. We take all feedback seriously and are committed to ensuring a positive experience for our users. Our intention is not to cause any offense or discomfort. We will review your feedback and assess how we can address the issues you've raised. Please understand that our program's purpose is to assist and provide valuable information to users. If you have any further details or specific points you'd like to highlight, please feel free to share them with us. We appreciate your understanding and look forward to finding a resolution that addresses your concerns.

Kind regards, Code Writer.

**Comment by jooapa** [comment]
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢉⢤⣢⡢⣉⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⠿⢋⢋⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⢡⡫⡣⡢⢫⢺⡂⣹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⠃⣜⢮⢳⠹⣕⠜⣿⡿⠿⠟⢛⢛⠛⡂⢯⣪⡸⡸⠕⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣷⡈⢮⡣⡱⡱⡸⣕⢤⡲⡺⣪⡳⡳⣝⢮⡳⡵⣝⢮⡢⣌⢍⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣷⡄⠉⣚⢮⡺⣪⡳⣝⣝⢮⢎⢯⣪⡳⣝⢞⢼⢕⣝⢮⡳⣝⢖⢤⡉⠻⢿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⡿⠋⣠⡺⣪⡳⣝⢮⡺⡪⡮⡳⣝⢵⢕⣝⢮⡫⡮⡳⣕⢗⣝⢮⣫⢳⢝⢵⢄⠙⢿⣿⣿⣿⣿⣿
⣿⣿⣿⠟⢁⡜⡮⣺⡪⣺⡪⡳⣝⢵⢝⢞⢮⡳⣣⡳⡳⣝⢮⡫⡮⡳⣕⢗⢵⢝⢵⢝⢕⣗⢄⠙⣿⣿⣿⣿
⣿⣿⠏⠀⡅⣆⢥⡳⣝⢮⢎⢯⣪⡳⣝⡕⣗⢝⢮⢎⢯⣪⡳⣝⢮⡫⡮⡫⡮⡫⡮⣔⢔⢌⢗⢥⠈⢻⣿⣿
⣿⠇⢠⢯⡺⣪⡳⣝⢮⡳⣝⢵⢕⢝⢎⣎⣎⢭⢕⣍⣇⢳⢹⢪⡳⣝⢮⡫⡮⣫⡺⡪⡯⣪⣫⡳⣕⠄⢻⣿
⡏⢀⡗⣕⣭⣮⣼⣸⠱⣝⠮⡣⣣⣳⣳⡳⡳⣝⣗⣗⢽⣕⢷⢕⢝⠼⣕⣝⢞⢜⣼⣼⣮⣎⡎⣞⢮⡣⠀⢿
⠁⢰⣱⣿⣿⣿⣿⣿⣷⢕⢵⢝⣞⣞⢞⢮⣻⣺⣺⣪⡳⡽⣝⣝⢷⢕⢕⢕⣵⣿⣿⣿⣿⣿⣿⡎⡧⣫⡃⠸
⠂⢱⣿⣿⠁⠉⣿⣿⡟⣕⣝⣗⢗⠁⠄⡑⣗⣗⣕⠇⡉⢉⠺⡪⡯⣯⢪⢱⣿⣿⣿⣿⡇⠀⣸⣿⢸⡪⣎⠀
⠀⢊⢿⣿⣷⣿⣿⣿⡇⣞⢞⢮⢇⠠⠁⡀⣗⣕⣗⠅⠐⡀⠂⡯⡯⡮⡇⡣⡻⣿⣿⣿⣿⣿⣿⢏⢪⡺⡜⠀
⡇⠨⡪⡹⠻⠿⠿⡻⡱⡸⡽⣝⣗⣄⣅⣔⣗⣗⣗⣗⢥⢤⢯⡫⡯⡯⡪⡺⣜⢌⢻⠻⡻⡫⡱⡸⣕⡝⡎⢠
⣧⠀⢣⢫⣹⡸⣱⡱⡵⣕⢝⢞⣞⢞⣞⢮⡺⣮⣺⡪⡯⡯⡳⡽⡽⡱⣕⣝⢮⡳⡵⡱⣕⢵⢝⢞⢮⡪⠀⣼
⣿⣧⡀⠣⡳⣝⢮⡺⡪⡮⡳⣕⢕⡓⡗⡗⡝⡞⡮⠯⡫⡫⡫⡹⣜⢞⣜⢮⡳⣝⢮⡫⡮⡳⣝⢕⠳⠀⣼⣿
⣿⣿⣷⣄⠈⠎⡗⡽⣕⣝⢞⢮⡳⡵⣱⢱⡱⡱⡪⡣⡳⡱⣝⢞⢮⡳⣕⢗⣝⢮⡳⣝⢮⡫⡪⠃⣠⣾⣿⣿
⣿⣿⣿⣿⣷⣄⠈⠊⢎⢎⢯⢳⢝⢞⢮⡳⣝⢞⢮⡫⡮⡫⡮⣫⡺⡪⡮⡳⣕⢗⢝⠎⠎⠈⣠⣶⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣦⣄⡈⠘⠘⠕⢍⢗⢝⢎⢯⢚⢎⢯⢪⢫⢪⢪⢫⠪⠪⠊⠊⣀⣤⣶⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣦⣤⣠⣀⣁⣈⢈⢈⢈⢈⣀⣁⣠⣠⣤⣶⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
